server:
  num_workers: 4
  cpu_affinity: true
  number_of_servers: 6
  host_range_start: 8100

services:
  # resnet18:        ["127.0.0.1:8500"]
  resnet50:        ["127.0.0.1:8501"]
  ssd:             ["127.0.0.1:8502"]
  # mobilenetv2:     ["127.0.0.1:8503"]
  # efficientnet_b0: ["127.0.0.1:8504"]
  # resnet34:        ["127.0.0.1:8505"]
  # resnet101:       ["127.0.0.1:8506"]
  # retinanet:       ["127.0.0.1:8507"]
  # fasterrcnn:      ["127.0.0.1:8508"]
  # maskrcnn:        ["127.0.0.1:8509"]




scheduler:
  host: 0.0.0.0
  port: 8000