server:
  max_service: 4
  cpu_affinity: true
  number_of_servers: 6
  host_range_start: 8100

services:
  mobilenetv2:     ["127.0.0.1:3"]
  # efficientnet_b0: ["127.0.0.1:4"]
  # resnet18:        ["127.0.0.1:1"]
  resnet34:        ["127.0.0.1:5"]
  # resnet50:        ["127.0.0.1:2"]
  # resnet101:       ["127.0.0.1:6"]
  ssd:             ["127.0.0.1:10"]
  # retinanet:       ["127.0.0.1:7"]
  # fasterrcnn:      ["127.0.0.1:8"]
  # maskrcnn:        ["127.0.0.1:9"]

scheduler:
  host: 0.0.0.0
  port: 11

drl:
  episodes: 1000
  max_steps: 200
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.995
  lr: 0.001
  batch_size: 64
  memory_size: 10000
  target_update: 10
  hidden_size: 128
  model_path: "drl_model.pth"

output:
  base_name: "output_file"

checkpoint:
  interval: 50
  model_path_dir: "../ckpt"
  
